// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKTd6c2wZkIk0X3GjbjoSCqlLuU7mHxeI',
    appId: '1:474212547216:web:567263242b77ce4fe47615',
    messagingSenderId: '474212547216',
    projectId: 'chat-wave-eea40',
    authDomain: 'chat-wave-eea40.firebaseapp.com',
    storageBucket: 'chat-wave-eea40.appspot.com',
    measurementId: 'G-N4JG70CG2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADxDSCpJig2nwzSmpaL9rSL8Jo82fbKTU',
    appId: '1:474212547216:android:00a742e187a4f455e47615',
    messagingSenderId: '474212547216',
    projectId: 'chat-wave-eea40',
    storageBucket: 'chat-wave-eea40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV2KrQazVy1-HS4R_jcZoACfTdJi5vQ-c',
    appId: '1:474212547216:ios:a0de083180787a29e47615',
    messagingSenderId: '474212547216',
    projectId: 'chat-wave-eea40',
    storageBucket: 'chat-wave-eea40.appspot.com',
    iosBundleId: 'com.example.chatWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV2KrQazVy1-HS4R_jcZoACfTdJi5vQ-c',
    appId: '1:474212547216:ios:a0de083180787a29e47615',
    messagingSenderId: '474212547216',
    projectId: 'chat-wave-eea40',
    storageBucket: 'chat-wave-eea40.appspot.com',
    iosBundleId: 'com.example.chatWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKTd6c2wZkIk0X3GjbjoSCqlLuU7mHxeI',
    appId: '1:474212547216:web:e3938c616ecebaabe47615',
    messagingSenderId: '474212547216',
    projectId: 'chat-wave-eea40',
    authDomain: 'chat-wave-eea40.firebaseapp.com',
    storageBucket: 'chat-wave-eea40.appspot.com',
    measurementId: 'G-JTMC3M7W25',
  );
}
